# Generated by Django 4.2.26 on 2025-11-20 07:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_processed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority_level', models.IntegerField(choices=[(1, 'Standard'), (2, 'High'), (3, 'Premium')], default=1, help_text='Determines feed placement priority')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total campaign budget in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_view', models.DecimalField(decimal_places=4, help_text='Cost per view in USD', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to=settings.AUTH_USER_MODEL)),
                ('sponsored_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_campaign', to='community.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('roi', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='promotions.sponsorcampaign')),
            ],
            options={
                'verbose_name_plural': 'Promotion Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('profile_view', 'Profile View'), ('group_join', 'Group Join'), ('post_create', 'Post Create')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.comment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.group')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='promotions.sponsorcampaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='promotions__status_14f150_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['sponsor', 'status'], name='promotions__sponsor_2e27be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionmetrics',
            unique_together={('campaign', 'date')},
        ),
        migrations.AddIndex(
            model_name='engagementlog',
            index=models.Index(fields=['action_type', 'created_at'], name='promotions__action__c2b4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementlog',
            index=models.Index(fields=['user', 'action_type'], name='promotions__user_id_bf5432_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignanalytics',
            unique_together={('campaign', 'date')},
        ),
    ]
