# Generated by Django 4.2.26 on 2025-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_sponsorcampaign_engagementlog_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engagementlog',
            index=models.Index(fields=['action_type', 'created_at'], name='promotions__action__c2b4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementlog',
            index=models.Index(fields=['user', 'action_type'], name='promotions__user_id_bf5432_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='promotions__status_14f150_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorcampaign',
            index=models.Index(fields=['sponsor', 'status'], name='promotions__sponsor_2e27be_idx'),
        ),
    ]
