# Generated by Django 4.2.26 on 2025-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_engagementlog_promotions__action__c2b4d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
