# Generated by Django 4.2.26 on 2025-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_sponsorcampaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementlog',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('profile_view', 'Profile View'), ('group_join', 'Group Join'), ('post_create', 'Post Create')], max_length=20),
        ),
    ]
