# Generated by Django 4.2.26 on 2025-11-15 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text="Lucide icon name, e.g., 'film' or 'tv'", max_length=50)),
                ('color_from', models.CharField(default='from-brand-red', help_text='Tailwind gradient color (from)', max_length=50)),
                ('color_to', models.CharField(default='to-red-700', help_text='Tailwind gradient color (to)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('youtube', 'YouTube Embed'), ('upload', 'Uploaded Video')], default='youtube', max_length=20)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL (used if content_type is youtube)', validators=[django.core.validators.URLValidator(), tv.models.validate_youtube_url])),
                ('video_file', models.FileField(blank=True, help_text='Video file (used if content_type is upload)', upload_to='videos/')),
                ('thumbnail', models.ImageField(help_text='Thumbnail image shown before video plays', upload_to='videos/thumbnails/')),
                ('duration', models.CharField(help_text='Duration in format: "45 min" or "1:30:00"', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this video prominently')),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='tv.videocategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
