# Generated by Django 4.2.26 on 2025-11-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCommunityMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_label', models.CharField(default='Our Mission', max_length=50)),
                ('mission_title', models.CharField(default='More Than a Forum', max_length=200)),
                ('mission_description', models.TextField(default="The New Africa Community is more than a forum — it's a continental movement uniting individuals and organizations across Africa and the diaspora into a single ecosystem of empowerment, visibility, and influence.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Community',
                'verbose_name_plural': 'About Community',
            },
        ),
        migrations.CreateModel(
            name='CommunityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('feature_type', models.CharField(choices=[('mentorship', 'Mentorship'), ('education', 'Education'), ('networking', 'Networking')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Feature',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(default=0)),
                ('active_groups', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_facilitators', models.IntegerField(default=0)),
                ('total_courses', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Metrics',
                'verbose_name_plural': 'Community Metrics',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FinalCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part_1', models.CharField(default='The future of Africa depends on those who', max_length=100)),
                ('title_teach', models.CharField(default='teach', max_length=50)),
                ('title_connect', models.CharField(default='connect', max_length=50)),
                ('title_empower', models.CharField(default='empower', max_length=50)),
                ('subtitle', models.CharField(default='Join the movement. Shape the narrative. Build the future.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final CTA',
                'verbose_name_plural': 'Final CTAs',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(default='One Million Voices.', max_length=100)),
                ('title_line_2', models.CharField(default='One Africa.', max_length=100)),
                ('title_line_3', models.CharField(default='One Movement.', max_length=100)),
                ('subtitle', models.TextField(default='Join a global community of Africans, innovators, facilitators, and leaders shaping tomorrow.')),
                ('individual_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('individual_period', models.CharField(default='Month', max_length=20)),
                ('facilitator_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('facilitator_period', models.CharField(default='Month', max_length=20)),
                ('corporate_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('corporate_period', models.CharField(default='Year', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('individual', 'Individual'), ('facilitator', 'Facilitator'), ('corporate', 'Corporate')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(help_text='e.g., Month, Year', max_length=20)),
                ('description', models.TextField()),
                ('label_color', models.CharField(default='text-cool-blue', max_length=50)),
                ('bg_color', models.CharField(default='bg-white', max_length=50)),
                ('button_color', models.CharField(default='bg-brand-red', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(help_text='e.g., Tech Entrepreneur, Nigeria', max_length=200)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide React icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='homepagecommunity.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Subscription Benefit',
                'ordering': ['tier', 'order'],
            },
        ),
    ]
