# Generated by Django 4.2.26 on 2025-11-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepagecommunity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
