# Generated by Django 4.2.26 on 2025-11-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepagecommunity', '0002_delete_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcommunitymission',
            name='icon_name',
            field=models.CharField(default='Lightbulb', help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='communityfeature',
            name='icon_name',
            field=models.CharField(default=1, help_text='Lucide React icon name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitymetrics',
            name='icon_name',
            field=models.CharField(default='BarChart3', help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='finalcta',
            name='icon_name',
            field=models.CharField(default='Rocket', help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='icon_name',
            field=models.CharField(default='Users', help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='icon_name',
            field=models.CharField(default=1, help_text='Lucide React icon name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='icon_name',
            field=models.CharField(default='Star', help_text='Lucide React icon name', max_length=50),
        ),
    ]
