# Generated by Django 4.2.26 on 2025-11-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepagecommunity', '0003_aboutcommunitymission_icon_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcommunitymission',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='communityfeature',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='communitymetrics',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='finalcta',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='icon_name',
        ),
    ]
