# Generated by Django 4.2.26 on 2025-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community/group_banners/'),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community/group_profiles/'),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
