# Generated by Django 5.2.7 on 2025-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_summitagendaitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summitagenda',
            options={'verbose_name': 'Summit Agenda', 'verbose_name_plural': 'Summit Agendas'},
        ),
        migrations.AlterModelOptions(
            name='summitagendaday',
            options={'ordering': ['order', 'date'], 'verbose_name': 'Agenda Day', 'verbose_name_plural': 'Agenda Days'},
        ),
        migrations.AlterModelOptions(
            name='summitagendaitem',
            options={'ordering': ['order', 'start_time'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='summitagendaday',
            old_name='parent',
            new_name='agenda',
        ),
        migrations.RemoveField(
            model_name='summitagenda',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='summitagenda',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='summitagenda',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='summitagenda',
            name='title_highlight',
        ),
        migrations.RemoveField(
            model_name='summitagenda',
            name='title_main',
        ),
        migrations.RemoveField(
            model_name='summitagendaday',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='summitagendaday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='summitagendaday',
            name='icon',
        ),
        migrations.AddField(
            model_name='summitagenda',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='summitagenda',
            name='title',
            field=models.CharField(default=1, help_text='Title of the summit/event', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summitagenda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='summitagendaday',
            name='activities_text',
            field=models.TextField(blank=True, help_text='Comma-separated activities in the format "HH:MM-HH:MM|Title"'),
        ),
        migrations.AddField(
            model_name='summitagendaitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summitagendaday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='summitagendaday',
            name='title',
            field=models.CharField(help_text='Title for this agenda day', max_length=255),
        ),
    ]
