# Generated by Django 5.2.7 on 2025-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_featuredspeaker_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='summit/past_editions/')),
                ('attendees', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
