# Generated by Django 5.2.7 on 2025-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_summitagenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitagendaday',
            name='color',
            field=models.CharField(blank=True, help_text='Optional gradient/color CSS classes for the day header', max_length=255),
        ),
        migrations.AddField(
            model_name='summitagendaday',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional emoji or icon name for this day', max_length=64),
        ),
    ]
