# Generated by Django 5.2.7 on 2025-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_summitagendaday_color_summitagendaday_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
