# Generated by Django 5.2.7 on 2025-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_registrationpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpackage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
