# Generated by Django 5.2.7 on 2025-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_registrationpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpackage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
