# Generated by Django 5.2.7 on 2025-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_media_and_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
