# Generated by Django 5.2.7 on 2025-11-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20251101_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpackage',
            name='color',
            field=models.CharField(blank=True, choices=[('from-blue-500 to-brand-blue', 'Blue gradient'), ('from-brand-gold to-yellow-600', 'Gold gradient'), ('from-purple-500 to-pink-500', 'Purple gradient'), ('from-green-500 to-emerald-500', 'Green gradient'), ('from-indigo-500 to-blue-500', 'Indigo gradient')], default='from-blue-500 to-brand-blue', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='icon',
            field=models.CharField(blank=True, choices=[('👥', 'People (👥)'), ('🌍', 'Globe (🌍)'), ('🎤', 'Microphone (🎤)'), ('📅', 'Calendar (📅)'), ('⭐', 'Star (⭐)'), ('💼', 'Briefcase (💼)'), ('📈', 'Chart (📈)')], default='👥', max_length=4),
        ),
    ]
