# Generated by Django 5.2.7 on 2025-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_registrationpackage_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpackage',
            name='icon',
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('from-blue-500 to-blue-600', 'Blue'), ('from-purple-500 to-purple-600', 'Purple'), ('from-green-500 to-green-600', 'Green'), ('from-emerald-500 to-emerald-600', 'Emerald'), ('from-orange-500 to-orange-600', 'Orange'), ('from-red-500 to-red-600', 'Red'), ('from-yellow-500 to-yellow-600', 'Yellow'), ('from-teal-500 to-teal-600', 'Teal'), ('from-indigo-500 to-indigo-600', 'Indigo'), ('from-blue-500 to-brand-blue', 'Blue gradient'), ('from-brand-gold to-yellow-600', 'Gold gradient'), ('from-purple-500 to-pink-500', 'Purple->Pink'), ('from-green-500 to-emerald-500', 'Green gradient'), ('from-indigo-500 to-blue-500', 'Indigo gradient')], default='from-blue-500 to-brand-blue', max_length=255),
        ),
    ]
