# Generated by Django 5.2.7 on 2025-10-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_postattachment_id'),
        ('community', '0008_comment_thread_private'),
    ]

    operations = [
    ]
