# Generated by Django 5.2.7 on 2025-10-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_merge_20251012_1342'),
        ('community', '0009_postbookmark'),
    ]

    operations = [
    ]
