# Generated by Django 5.2.7 on 2025-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_registrationpackage_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_section_title', models.CharField(blank=True, help_text='Section title (e.g. Become a Partner)', max_length=255)),
                ('partner_section_subtitle', models.TextField(blank=True, help_text='Smaller paragraph under the title')),
                ('partner_cta_label', models.CharField(blank=True, help_text='CTA button label', max_length=255)),
                ('partner_cta_url', models.URLField(blank=True, help_text='CTA button URL')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
