# Generated by Django 5.2.7 on 2025-10-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_merge_0009_merge_20251012_1342_0009_postbookmark'),
        ('community', '0010_post_link_previews'),
    ]

    operations = [
    ]
