# Generated by Django 5.2.7 on 2025-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_partnersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='New Africa', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=512)),
                ('address_text', models.CharField(blank=True, max_length=512)),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('footer_sections', models.JSONField(blank=True, default=list)),
                ('bottom_links', models.JSONField(blank=True, default=list)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
