# Generated by Django 5.2.7 on 2025-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_footercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontent',
            name='bottom_links',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='footer_sections',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='social_links',
        ),
        migrations.AddField(
            model_name='footercontent',
            name='account_faqs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='account_login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='account_signup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='company_about',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='company_careers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='company_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='company_team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='legal_help',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='legal_privacy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='legal_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='platforms_community',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='platforms_institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='platforms_magazine',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='platforms_summit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='platforms_tv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='social_facebook',
            field=models.CharField(blank=True, help_text='Facebook page URL', max_length=512),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='social_instagram',
            field=models.CharField(blank=True, help_text='Instagram page URL', max_length=512),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='social_linkedin',
            field=models.CharField(blank=True, help_text='LinkedIn page URL', max_length=512),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='social_twitter',
            field=models.CharField(blank=True, help_text='Twitter page URL', max_length=512),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='social_youtube',
            field=models.CharField(blank=True, help_text='YouTube channel URL', max_length=512),
        ),
    ]
