# Generated by Django 5.2.7 on 2025-10-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_merge_20251012_1418'),
        ('community', '0011_reactions'),
    ]

    operations = [
    ]
