# Generated by Django 5.2.7 on 2025-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_remove_footercontent_bottom_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(help_text='Primary headline shown on the About page', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting paragraph shown below the headline')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('cta_label', models.CharField(blank=True, help_text='Optional CTA label', max_length=255)),
                ('cta_url', models.URLField(blank=True, help_text='Optional CTA URL')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
