# Generated by Django 5.2.7 on 2025-11-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_abouthero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouthero',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='abouthero',
            name='cta_url',
        ),
    ]
