# Generated by Django 5.2.7 on 2025-10-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_commentreaction_id_alter_commentreaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed_visibility',
            field=models.CharField(choices=[('group_only', 'Group only'), ('public_global', 'Public global'), ('private', 'Private (only author)')], default='group_only', max_length=20),
        ),
    ]
