# Generated by Django 5.2.7 on 2025-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_remove_abouthero_cta_label_remove_abouthero_cta_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, help_text='Small badge text shown above the title (e.g. Join Our Community)', max_length=255)),
                ('title_main', models.CharField(help_text='Primary title text (before the highlighted part)', max_length=255)),
                ('title_highlight', models.CharField(blank=True, help_text='Highlighted part of the title shown in gradient', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/hero/')),
                ('stat1_value', models.CharField(blank=True, help_text='Stat 1 value (e.g. 95%)', max_length=64)),
                ('stat1_label', models.CharField(blank=True, help_text='Stat 1 label (e.g. Growth Rate)', max_length=128)),
                ('stat2_value', models.CharField(blank=True, help_text='Stat 2 value (e.g. 1M+)', max_length=64)),
                ('stat2_label', models.CharField(blank=True, help_text='Stat 2 label (e.g. Members)', max_length=128)),
                ('stat3_value', models.CharField(blank=True, help_text='Stat 3 value (e.g. 50+)', max_length=64)),
                ('stat3_label', models.CharField(blank=True, help_text='Stat 3 label (e.g. Countries)', max_length=128)),
                ('card1_title', models.CharField(blank=True, max_length=255)),
                ('card1_description', models.TextField(blank=True)),
                ('card1_feature_1', models.CharField(blank=True, max_length=255)),
                ('card1_feature_2', models.CharField(blank=True, max_length=255)),
                ('card2_title', models.CharField(blank=True, max_length=255)),
                ('card2_description', models.TextField(blank=True)),
                ('card2_feature_1', models.CharField(blank=True, max_length=255)),
                ('card2_feature_2', models.CharField(blank=True, max_length=255)),
                ('cta_label', models.CharField(blank=True, max_length=255)),
                ('cta_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
