# Generated by Django 5.2.7 on 2025-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_communitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, help_text='Small label above the title (e.g. Ready to Get Started?)', max_length=255)),
                ('title_main', models.CharField(help_text='Primary title text', max_length=255)),
                ('title_highlight', models.CharField(blank=True, help_text='Highlighted part of the title', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=255)),
                ('primary_cta_url', models.URLField(blank=True)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_url', models.URLField(blank=True)),
                ('feature1_title', models.CharField(blank=True, max_length=128)),
                ('feature1_subtitle', models.CharField(blank=True, max_length=255)),
                ('feature2_title', models.CharField(blank=True, max_length=128)),
                ('feature2_subtitle', models.CharField(blank=True, max_length=255)),
                ('feature3_title', models.CharField(blank=True, max_length=128)),
                ('feature3_subtitle', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
