# Generated by Django 5.2.7 on 2025-11-05 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0017_videocategory_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('group_join', 'Group Join'), ('post_create', 'Post Create')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.comment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.group')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='community.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='community_e_action__eb8b2d_idx'), models.Index(fields=['user', 'action_type'], name='community_e_user_id_9a9d45_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority_level', models.IntegerField(choices=[(1, 'Standard'), (2, 'High'), (3, 'Premium')], default=1, help_text='Determines feed placement priority')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total campaign budget in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_view', models.DecimalField(decimal_places=4, help_text='Cost per view in USD', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to=settings.AUTH_USER_MODEL)),
                ('sponsored_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_campaign', to='community.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date', 'end_date'], name='community_s_status_4d3b91_idx'), models.Index(fields=['sponsor', 'status'], name='community_s_sponsor_d83e04_idx')],
            },
        ),
    ]
