# Generated by Django 4.2.26 on 2025-11-06 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0021_auto_20251106_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corporateconnection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footercontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Footer Content', 'verbose_name_plural': 'Footer Content'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='partnerdirectory',
            options={'verbose_name_plural': 'Partner Directory'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='registrationpackage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Registration Package', 'verbose_name_plural': 'Registration Packages'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='courseenrollment',
            old_name='created_at',
            new_name='enrolled_at',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='community_e_action__a66d0d_idx',
            old_name='community_e_action__eb8b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='community_e_user_id_522303_idx',
            old_name='community_e_user_id_9a9d45_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorcampaign',
            new_name='community_s_status_62d080_idx',
            old_name='community_s_status_4d3b91_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorcampaign',
            new_name='community_s_sponsor_31ecba_idx',
            old_name='community_s_sponsor_d83e04_idx',
        ),
        migrations.RemoveField(
            model_name='corporateconnection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='partnerdirectory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnerdirectory',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='partnerdirectory',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='partnerdirectory',
            name='website',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='performance_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='corporateconnection',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporateconnection',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('project', 'Project'), ('collaboration', 'Collaboration'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='industry_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='showcase_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='social_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='partnerdirectory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='account_faqs',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='account_login',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='account_signup',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address_text',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='company_about',
            field=models.URLField(blank=True, default=1, help_text='About Us page URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='company_careers',
            field=models.URLField(blank=True, default=1, help_text='Careers page URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='company_contact',
            field=models.URLField(blank=True, default=1, help_text='Contact Us page URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='company_name',
            field=models.CharField(default=1, help_text='Company name shown in footer', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='company_team',
            field=models.URLField(blank=True, default=1, help_text='Team page URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='contact_email',
            field=models.EmailField(blank=True, default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='legal_help',
            field=models.URLField(blank=True, default=1, help_text='Help/Support URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='legal_privacy',
            field=models.URLField(blank=True, default=1, help_text='Privacy Policy URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='legal_terms',
            field=models.URLField(blank=True, default=1, help_text='Terms of Service URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='platforms_community',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='platforms_institute',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='platforms_magazine',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='platforms_summit',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='platforms_tv',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='social_facebook',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='social_instagram',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='social_linkedin',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='social_twitter',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='social_youtube',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='tagline',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerdirectory',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directory_listing', to='community.corporateverification'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('from-blue-500 to-blue-600', 'Blue'), ('from-purple-500 to-purple-600', 'Purple'), ('from-green-500 to-green-600', 'Green'), ('from-emerald-500 to-emerald-600', 'Emerald'), ('from-orange-500 to-orange-600', 'Orange'), ('from-red-500 to-red-600', 'Red'), ('from-yellow-500 to-yellow-600', 'Yellow'), ('from-teal-500 to-teal-600', 'Teal'), ('from-indigo-500 to-indigo-600', 'Indigo'), ('from-blue-500 to-brand-blue', 'Blue gradient'), ('from-brand-gold to-yellow-600', 'Gold gradient'), ('from-purple-500 to-pink-500', 'Purple->Pink'), ('from-green-500 to-emerald-500', 'Green gradient'), ('from-indigo-500 to-blue-500', 'Indigo gradient')], default=1, help_text='Optional gradient color class for the package card', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='features',
            field=models.JSONField(default=list, help_text='List of features included in this package'),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='popular',
            field=models.BooleanField(default=False, help_text='Whether to highlight this as a popular option'),
        ),
        migrations.AlterField(
            model_name='registrationpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('facilitator', 'Facilitator'), ('corporate', 'Corporate'), ('admin', 'Admin')], default='individual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='community_p_created_6febb2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-ranking_score'], name='community_p_ranking_5613c2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='community_p_author__c7cd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group', '-created_at'], name='community_p_group_i_f2b7bd_idx'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
