# Generated by Django 4.2.26 on 2025-11-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_useractivity_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='facilitator',
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeaturedSpeaker',
        ),
        migrations.DeleteModel(
            name='FooterContent',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerSection',
        ),
        migrations.DeleteModel(
            name='PastEdition',
        ),
        migrations.DeleteModel(
            name='RegistrationPackage',
        ),
        migrations.RemoveField(
            model_name='summitagendaday',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='summitagendaitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='summitpillar',
            name='about',
        ),
        migrations.RemoveField(
            model_name='summitstat',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='summittheme',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
