# Generated by Django 4.2.26 on 2025-11-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_remove_campaign_owner_remove_course_facilitator_and_more'),
        ('promotions', '0002_sponsorcampaign_engagementlog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='EngagementLog',
        ),
        migrations.DeleteModel(
            name='SponsorCampaign',
        ),
        migrations.DeleteModel(
            name='SummitAbout',
        ),
        migrations.DeleteModel(
            name='SummitAgenda',
        ),
        migrations.DeleteModel(
            name='SummitAgendaDay',
        ),
        migrations.DeleteModel(
            name='SummitAgendaItem',
        ),
        migrations.DeleteModel(
            name='SummitHero',
        ),
        migrations.DeleteModel(
            name='SummitKeyThemes',
        ),
        migrations.DeleteModel(
            name='SummitPillar',
        ),
        migrations.DeleteModel(
            name='SummitStat',
        ),
        migrations.DeleteModel(
            name='SummitTheme',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
