# Generated by Django 4.2.26 on 2025-11-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_delete_campaign_delete_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
