# Generated by Django 4.2.26 on 2025-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_add_withdrawal_request_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutHero',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
