# Generated by Django 4.2.26 on 2025-11-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_corporateopportunity_platformanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsored_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.sponsoredpost'),
        ),
    ]
