# Generated by Django 4.2.26 on 2025-11-16 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0030_add_message_field_to_corporateconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('like_post', 'Liked a Post'), ('unlike_post', 'Unliked a Post'), ('like_comment', 'Liked a Comment'), ('unlike_comment', 'Unliked a Comment'), ('comment_post', 'Commented on Post'), ('reply_comment', 'Replied to Comment'), ('mention_user', 'Mentioned a User'), ('join_group', 'Joined Group'), ('leave_group', 'Left Group'), ('view_post', 'Viewed Post'), ('share_post', 'Shared Post'), ('bookmark_post', 'Bookmarked Post'), ('unbookmark_post', 'Unbookmarked Post')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_engagement_logs', to='community.comment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_engagement_logs', to='community.group')),
                ('mentioned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_engagement_logs', to='community.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_engagement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Community Engagement Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_score', models.IntegerField(default=0)),
                ('activity_level', models.CharField(choices=[('inactive', 'Inactive'), ('novice', 'Novice'), ('active', 'Active'), ('power_user', 'Power User'), ('community_leader', 'Community Leader')], default='novice', max_length=20)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('total_engagement_actions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Reputations',
            },
        ),
        migrations.CreateModel(
            name='MentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='community.comment')),
                ('mentioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions_made', to=settings.AUTH_USER_MODEL)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_in_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='community.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentioned_user', '-created_at'], name='community_m_mention_37161d_idx'), models.Index(fields=['post', 'mentioned_user'], name='community_m_post_id_8e170c_idx'), models.Index(fields=['comment', 'mentioned_user'], name='community_m_comment_51ed77_idx')],
            },
        ),
        migrations.CreateModel(
            name='EngagementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('post_liked', 'Your post was liked'), ('post_commented', 'Someone commented on your post'), ('comment_liked', 'Your comment was liked'), ('comment_replied', 'Someone replied to your comment'), ('post_mentioned', 'You were mentioned in a post'), ('comment_mentioned', 'You were mentioned in a comment'), ('group_update', 'New activity in your group')], max_length=32)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communityengagementlog')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='community_e_user_id_9e1e58_idx'), models.Index(fields=['user', 'read', '-created_at'], name='community_e_user_id_f815f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='communityengagementlog',
            index=models.Index(fields=['user', '-created_at'], name='community_c_user_id_7123e5_idx'),
        ),
        migrations.AddIndex(
            model_name='communityengagementlog',
            index=models.Index(fields=['action_type', '-created_at'], name='community_c_action__b1c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='communityengagementlog',
            index=models.Index(fields=['post', 'action_type'], name='community_c_post_id_8f9174_idx'),
        ),
        migrations.AddIndex(
            model_name='communityengagementlog',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='community_c_mention_0c3d14_idx'),
        ),
        migrations.AddIndex(
            model_name='communityengagementlog',
            index=models.Index(fields=['user', 'action_type', '-created_at'], name='community_c_user_id_001da0_idx'),
        ),
    ]
