# Generated by Django 4.2.26 on 2025-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_published_course_preview_video_url_and_more'),
        ('community', '0034_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='community_groups', to='courses.course'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('general', 'General Discussion'), ('announcement', 'Announcement'), ('event', 'Event'), ('job_posting', 'Job Posting'), ('resource', 'Resource'), ('question', 'Question')], default='general', max_length=50),
        ),
    ]
