# Generated by Django 4.2.26 on 2025-11-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_group_courses_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateverification',
            name='additional_docs',
            field=models.JSONField(blank=True, default=list, help_text='Additional document URLs/metadata'),
        ),
        migrations.AddField(
            model_name='corporateverification',
            name='business_registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='corporate_verification/documents/'),
        ),
        migrations.AddField(
            model_name='corporateverification',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporateverification',
            name='tax_certificate_doc',
            field=models.FileField(blank=True, null=True, upload_to='corporate_verification/documents/'),
        ),
    ]
