# Generated by Django 4.2.26 on 2025-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_corporatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateopportunity',
            name='requirements',
            field=models.TextField(blank=True, help_text='Comma-separated list of requirements'),
        ),
        migrations.AlterField(
            model_name='communityengagementlog',
            name='action_type',
            field=models.CharField(choices=[('click_action', 'Clicked Action'), ('like_post', 'Liked a Post'), ('unlike_post', 'Unliked a Post'), ('like_comment', 'Liked a Comment'), ('unlike_comment', 'Unliked a Comment'), ('comment_post', 'Commented on Post'), ('reply_comment', 'Replied to Comment'), ('mention_user', 'Mentioned a User'), ('join_group', 'Joined Group'), ('leave_group', 'Left Group'), ('view_post', 'Viewed Post'), ('share_post', 'Shared Post'), ('bookmark_post', 'Bookmarked Post'), ('unbookmark_post', 'Unbookmarked Post')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
