# Generated by Django 4.2.26 on 2025-11-18 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0038_corporateopportunity_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='approved_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='rejected_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='reviewer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['opportunity', 'status'], name='community_o_opportu_6f6c96_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['applicant', 'status'], name='community_o_applica_04041e_idx'),
        ),
    ]
