# Generated by Django 4.2.26 on 2025-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
