# Generated by Django 4.2.26 on 2025-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
