# Generated by Django 5.2.7 on 2025-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_corporateverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community_approved',
            field=models.BooleanField(default=False),
        ),
    ]
