# Generated by Django 4.2.26 on 2025-11-08 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_revenue_target', models.DecimalField(decimal_places=2, default=5000.0, help_text='Monthly revenue target for facilitators (in $)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('student_target', models.IntegerField(default=100, help_text='Target number of students per facilitator', validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_rating_target', models.FloatField(default=4.0, help_text='Minimum acceptable rating for courses', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('ideal_rating_target', models.FloatField(default=4.5, help_text='Ideal rating target for courses', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('lesson_completion_target', models.IntegerField(default=80, help_text='Target lesson completion rate (percentage)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('analytics_time_period', models.IntegerField(default=30, help_text='Default time period for analytics in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('progress_warning_threshold', models.IntegerField(default=60, help_text='Threshold percentage below which progress bars show warning color', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('progress_success_threshold', models.IntegerField(default=80, help_text='Threshold percentage above which progress bars show success color', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('dashboard_refresh_interval', models.IntegerField(default=30, help_text='Dashboard auto-refresh interval in seconds', validators=[django.core.validators.MinValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='FacilitatorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_revenue_target', models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly revenue target (leave blank to use global)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_student_target', models.IntegerField(blank=True, help_text='Custom student target (leave blank to use global)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('custom_rating_target', models.FloatField(blank=True, help_text='Custom rating target (leave blank to use global)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('custom_engagement_target', models.IntegerField(blank=True, help_text='Custom engagement target percentage (leave blank to use global)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, help_text="Notes about this facilitator's targets")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facilitator Target',
                'verbose_name_plural': 'Facilitator Targets',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('period_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_growth', models.FloatField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('student_growth', models.FloatField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('rating_growth', models.FloatField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('engagement_growth', models.FloatField(default=0)),
                ('report_data', models.JSONField(default=dict, help_text='Full report data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Report',
                'verbose_name_plural': 'Analytics Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
