# Generated by Django 5.2.7 on 2025-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Technology', 'Technology'), ('Creative', 'Creative'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('Online', 'Online'), ('Self-paced', 'Self-paced'), ('Live', 'Live'), ('Hybrid', 'Hybrid')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
