# Generated by Django 4.2.26 on 2025-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachments_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='auto_grade_on_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_types_allowed',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='late_submission_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='late_submission_days',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_word_count',
            field=models.PositiveIntegerField(blank=True, default=5000, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='min_word_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='points_total',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rubric',
            field=models.TextField(blank=True, null=True),
        ),
    ]
