# Generated by Django 4.2.26 on 2025-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_attachments_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.TextField(default='[]'),
        ),
    ]
