# Generated by Django 4.2.26 on 2025-11-29 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_add_completed_lessons_to_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='coursereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('course', 'user')},
        ),
    ]
