# Generated by Django 4.2.26 on 2025-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursereview_options_coursereview_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='availability_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when this lesson becomes available to students', null=True),
        ),
    ]
