# Generated by Django 4.2.26 on 2025-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
