# Generated by Django 4.2.26 on 2025-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
