# Generated by Django 4.2.26 on 2025-11-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='summit/speakers/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='summit/organizers/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_section_title', models.CharField(blank=True, help_text='Section title (e.g. Become a Partner)', max_length=255)),
                ('partner_section_subtitle', models.TextField(blank=True, help_text='Smaller paragraph under the title')),
                ('partner_cta_label', models.CharField(blank=True, help_text='CTA button label', max_length=255)),
                ('partner_cta_url', models.URLField(blank=True, help_text='CTA button URL')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='summit/past_editions/')),
                ('attendees', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('features', models.JSONField(default=list, help_text='List of features included in this package')),
                ('popular', models.BooleanField(default=False, help_text='Whether to highlight this as a popular option')),
                ('color', models.CharField(blank=True, choices=[('', 'Default'), ('from-blue-500 to-blue-600', 'Blue'), ('from-purple-500 to-purple-600', 'Purple'), ('from-green-500 to-green-600', 'Green'), ('from-emerald-500 to-emerald-600', 'Emerald'), ('from-orange-500 to-orange-600', 'Orange'), ('from-red-500 to-red-600', 'Red'), ('from-yellow-500 to-yellow-600', 'Yellow'), ('from-teal-500 to-teal-600', 'Teal'), ('from-indigo-500 to-indigo-600', 'Indigo'), ('from-blue-500 to-brand-blue', 'Blue gradient'), ('from-brand-gold to-yellow-600', 'Gold gradient'), ('from-purple-500 to-pink-500', 'Purple->Pink'), ('from-green-500 to-emerald-500', 'Green gradient'), ('from-indigo-500 to-blue-500', 'Indigo gradient')], help_text='Optional gradient color class for the package card', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Package',
                'verbose_name_plural': 'Registration Packages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SummitAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(help_text="Primary title (e.g. Building Africa's)", max_length=255)),
                ('title_highlight', models.CharField(blank=True, help_text='Highlighted part of the title', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='summit/about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummitAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the summit/event', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summit Agenda',
                'verbose_name_plural': 'Summit Agendas',
            },
        ),
        migrations.CreateModel(
            name='SummitAgendaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this agenda day', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('activities_text', models.TextField(blank=True, help_text='Comma-separated activities in the format "HH:MM-HH:MM|Title"')),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or icon name for this day', max_length=64)),
                ('color', models.CharField(blank=True, help_text='Optional gradient/color CSS classes for the day header', max_length=255)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='summit.summitagenda')),
            ],
            options={
                'verbose_name': 'Agenda Day',
                'verbose_name_plural': 'Agenda Days',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='SummitHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(help_text='Primary title (e.g. The New Africa)', max_length=255)),
                ('title_highlight', models.CharField(blank=True, help_text='Highlighted part of the title', max_length=255)),
                ('date_text', models.CharField(blank=True, help_text='Human-readable date (e.g. October 7-11, 2025)', max_length=255)),
                ('location_text', models.CharField(blank=True, help_text='Location text (e.g. Casablanca & Dakhla, Morocco)', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Bigger subtitle / description shown under the title')),
                ('strapline', models.CharField(blank=True, help_text='Short strapline shown under subtitle', max_length=255)),
                ('cta_register_label', models.CharField(blank=True, help_text='Label text for the register CTA button', max_length=255)),
                ('cta_register_url', models.URLField(blank=True)),
                ('cta_brochure_label', models.CharField(blank=True, help_text='Label text for the brochure CTA button', max_length=255)),
                ('cta_brochure_url', models.URLField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='summit/hero/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummitKeyThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(default='2025 Key', help_text='Primary part of the section title', max_length=255)),
                ('title_highlight', models.CharField(default='Themes', help_text='Highlighted part of the title', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cta_label', models.CharField(blank=True, help_text='Label for the CTA button (e.g. "Explore Full Programme Details")', max_length=255)),
                ('cta_url', models.URLField(blank=True, help_text='URL for the CTA button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummitTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Bot', 'AI Bot'), ('GraduationCap', 'Education'), ('Handshake', 'Partnership'), ('Sprout', 'Growth'), ('TrendingUp', 'Trends')], default='Bot', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('from-blue-500 to-blue-600', 'Blue'), ('from-purple-500 to-purple-600', 'Purple'), ('from-green-500 to-green-600', 'Green'), ('from-emerald-500 to-emerald-600', 'Emerald'), ('from-orange-500 to-orange-600', 'Orange'), ('from-red-500 to-red-600', 'Red'), ('from-yellow-500 to-yellow-600', 'Yellow'), ('from-teal-500 to-teal-600', 'Teal'), ('from-indigo-500 to-indigo-600', 'Indigo')], default='from-blue-500 to-blue-600', help_text='Choose a gradient color for the theme card', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='summit.summitkeythemes')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SummitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('👥', 'People (👥)'), ('🌍', 'Globe (🌍)'), ('🎤', 'Microphone (🎤)'), ('📅', 'Calendar (📅)'), ('⭐', 'Star (⭐)'), ('💼', 'Briefcase (💼)'), ('📈', 'Chart (📈)')], default='👥', max_length=4)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Ordering for display (lower numbers first)')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='summit.summithero')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SummitPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Target', 'Target'), ('Compass', 'Compass'), ('Lightbulb', 'Lightbulb'), ('Users', 'Users'), ('Globe', 'Globe')], default='Lightbulb', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='summit.summitabout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SummitAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='summit.summitagendaday')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
