# Generated by Django 4.2.26 on 2025-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitstat',
            name='icon',
            field=models.CharField(choices=[('👥', 'People'), ('🌍', 'Globe'), ('🎤', 'Microphone'), ('📅', 'Calendar'), ('⭐', 'Star'), ('💼', 'Briefcase'), ('📈', 'Chart')], default='👥', max_length=4),
        ),
    ]
