# Generated by Django 4.2.26 on 2025-11-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(help_text='Primary headline shown on the About page', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting paragraph shown below the headline')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('requirements', models.TextField(blank=True)),
                ('how_to_apply', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(help_text='Main contact email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Main contact phone number', max_length=50)),
                ('contact_hours', models.CharField(default='Mon-Fri, 9AM-6PM EAT', help_text='Business hours', max_length=100)),
                ('headquarters_address', models.CharField(help_text='Main headquarters location', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('inquiry_type', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company name shown in footer', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('address_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('company_about', models.URLField(blank=True, help_text='About Us page URL')),
                ('company_team', models.URLField(blank=True, help_text='Team page URL')),
                ('company_careers', models.URLField(blank=True, help_text='Careers page URL')),
                ('company_contact', models.URLField(blank=True, help_text='Contact Us page URL')),
                ('platforms_magazine', models.URLField(blank=True)),
                ('platforms_tv', models.URLField(blank=True)),
                ('platforms_institute', models.URLField(blank=True)),
                ('platforms_summit', models.URLField(blank=True)),
                ('platforms_community', models.URLField(blank=True)),
                ('account_login', models.URLField(blank=True)),
                ('account_signup', models.URLField(blank=True)),
                ('account_faqs', models.URLField(blank=True)),
                ('legal_terms', models.URLField(blank=True, help_text='Terms of Service URL')),
                ('legal_privacy', models.URLField(blank=True, help_text='Privacy Policy URL')),
                ('legal_help', models.URLField(blank=True, help_text='Help/Support URL')),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type', models.CharField(help_text='E.g. Headquarters, Regional Office', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='utils.contactdetails')),
            ],
            options={
                'ordering': ['order', 'city'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_contacts', to='utils.contactdetails')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
