# Generated by Django 5.2.7 on 2025-11-01 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact email address', max_length=254)),
                ('primary_phone', models.CharField(blank=True, help_text='Main contact phone number', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Primary office/mailing address')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('business_hours', models.CharField(blank=True, help_text='E.g. Mon-Fri: 9:00 AM - 5:00 PM', max_length=255)),
                ('general_inquiries_text', models.TextField(blank=True, help_text='Text shown above contact methods for general inquiries')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='social_links',
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='team/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='E.g. Sales, Support, Media Relations', max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about contacting this department')),
                ('order', models.IntegerField(default=0)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_contacts', to='utils.contactdetails')),
            ],
            options={
                'ordering': ['order', 'department'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Headquarters, Regional Office', max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.IntegerField(default=0)),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='utils.contactdetails')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
