# Generated by Django 5.2.7 on 2025-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_contactdetails_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentcontact',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='officelocation',
            options={'ordering': ['order', 'city']},
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='primary_email',
            new_name='main_email',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='primary_phone',
            new_name='main_phone',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='address',
            new_name='primary_address',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='facebook_url',
            new_name='social_facebook',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='instagram_url',
            new_name='social_instagram',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='linkedin_url',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='twitter_url',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='officelocation',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='general_inquiries_text',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='departmentcontact',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='departmentcontact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='officelocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officelocation',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown under contact methods'),
        ),
        migrations.AddField(
            model_name='departmentcontact',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officelocation',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officelocation',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
