# Generated by Django 5.2.7 on 2025-11-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_departmentcontact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='main_email',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='main_phone',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='primary_address',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='social_twitter',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='contact_email',
            field=models.EmailField(default=1, help_text='Main contact email address', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='contact_hours',
            field=models.CharField(default='Mon-Fri, 9AM-6PM EAT', help_text='Business hours', max_length=100),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='contact_phone',
            field=models.CharField(default=1, help_text='Main contact phone number', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='headquarters_address',
            field=models.CharField(default=1, help_text='Main headquarters location', max_length=255),
            preserve_default=False,
        ),
    ]
