# Generated by Django 5.2.7 on 2025-11-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_remove_contactdetails_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
    ]
