# Generated by Django 4.2.26 on 2025-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_teammember_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company name shown in footer', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('address_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('company_about', models.URLField(blank=True, help_text='About Us page URL')),
                ('company_team', models.URLField(blank=True, help_text='Team page URL')),
                ('company_careers', models.URLField(blank=True, help_text='Careers page URL')),
                ('company_contact', models.URLField(blank=True, help_text='Contact Us page URL')),
                ('platforms_magazine', models.URLField(blank=True)),
                ('platforms_tv', models.URLField(blank=True)),
                ('platforms_institute', models.URLField(blank=True)),
                ('platforms_summit', models.URLField(blank=True)),
                ('platforms_community', models.URLField(blank=True)),
                ('account_login', models.URLField(blank=True)),
                ('account_signup', models.URLField(blank=True)),
                ('account_faqs', models.URLField(blank=True)),
                ('legal_terms', models.URLField(blank=True, help_text='Terms of Service URL')),
                ('legal_privacy', models.URLField(blank=True, help_text='Privacy Policy URL')),
                ('legal_help', models.URLField(blank=True, help_text='Help/Support URL')),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
