# Generated by Django 4.2.26 on 2025-11-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_footercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(help_text='Primary headline shown on the About page', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting paragraph shown below the headline')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
